"""Fresh schema: teams, employees, performance, kpi

Revision ID: 975c072657f1
Revises: 
Create Date: 2026-06-20 18:54:51.957717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '975c072657f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_employees_external_id'), table_name='employees')
    op.drop_index(op.f('idx_employees_name_trgm'), table_name='employees', postgresql_using='gin')
    op.drop_index(op.f('idx_employees_team_id'), table_name='employees')
    op.drop_index(op.f('idx_kpi_under'), table_name='kpi_values', postgresql_where='(achievement_ratio < 1.0)')
    op.drop_index(op.f('idx_kpi_values_record_id'), table_name='kpi_values')
    op.drop_constraint(op.f('uq_kpi_value_record_key'), 'kpi_values', type_='unique')
    op.create_foreign_key(None, 'kpi_values', 'performance_records', ['record_id', 'record_year'], ['id', 'year'], ondelete='CASCADE')
    op.alter_column('performance_records', 'grade',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='grade_class'),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('performance_records', 'status',
               existing_type=postgresql.ENUM('Exceeds', 'Meets', 'Below', name='perf_status'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('performance_records', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_perf_employee_id'), table_name='performance_records')
    op.drop_index(op.f('idx_perf_employee_year'), table_name='performance_records')
    op.drop_index(op.f('idx_perf_grade'), table_name='performance_records')
    op.drop_index(op.f('idx_perf_score_desc'), table_name='performance_records')
    op.drop_index(op.f('idx_perf_team_month_year'), table_name='performance_records')
    op.drop_constraint(op.f('uq_perf_employee_month_year'), 'performance_records', type_='unique')
    op.alter_column('team_kpi_config', 'direction',
               existing_type=postgresql.ENUM('higher_better', 'lower_better', name='kpi_direction'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'higher_better'::kpi_direction"),
               server_default='higher_better')
    op.alter_column('team_kpi_config', 'unit',
               existing_type=postgresql.ENUM('%', 'currency', 'number', 'min', name='kpi_unit'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'%%'::kpi_unit"),
               server_default='%')
    op.alter_column('team_kpi_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_kpi_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_kpi_team_key'), 'team_kpi_config', type_='unique')
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_log', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='upload_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::upload_status"),
               server_default='pending')
    op.alter_column('upload_log', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_upload_created_at'), table_name='upload_log')
    op.drop_index(op.f('idx_upload_status'), table_name='upload_log', postgresql_where="(status = 'pending'::upload_status)")
    op.drop_index(op.f('idx_upload_team_month_year'), table_name='upload_log')
    op.drop_constraint(op.f('uq_upload_team_month_year'), 'upload_log', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_upload_team_month_year'), 'upload_log', ['team_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_upload_team_month_year'), 'upload_log', ['team_id', 'month', 'year'], unique=False)
    op.create_index(op.f('idx_upload_status'), 'upload_log', ['status'], unique=False, postgresql_where="(status = 'pending'::upload_status)")
    op.create_index(op.f('idx_upload_created_at'), 'upload_log', [sa.literal_column('uploaded_at DESC')], unique=False)
    op.alter_column('upload_log', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('upload_log', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'success', 'failed', name='upload_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::upload_status"))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_kpi_team_key'), 'team_kpi_config', ['team_id', 'kpi_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('team_kpi_config', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_kpi_config', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_kpi_config', 'unit',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('%', 'currency', 'number', 'min', name='kpi_unit'),
               existing_nullable=False,
               existing_server_default=sa.text("'%%'::kpi_unit"))
    op.alter_column('team_kpi_config', 'direction',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('higher_better', 'lower_better', name='kpi_direction'),
               existing_nullable=False,
               existing_server_default=sa.text("'higher_better'::kpi_direction"))
    op.create_unique_constraint(op.f('uq_perf_employee_month_year'), 'performance_records', ['employee_id', 'month', 'year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_perf_team_month_year'), 'performance_records', ['team_id', 'year', 'month'], unique=False)
    op.create_index(op.f('idx_perf_score_desc'), 'performance_records', ['team_id', sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('idx_perf_grade'), 'performance_records', ['grade', 'year', 'month'], unique=False)
    op.create_index(op.f('idx_perf_employee_year'), 'performance_records', ['employee_id', 'year'], unique=False)
    op.create_index(op.f('idx_perf_employee_id'), 'performance_records', ['employee_id'], unique=False)
    op.alter_column('performance_records', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_records', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('Exceeds', 'Meets', 'Below', name='perf_status'),
               existing_nullable=False)
    op.alter_column('performance_records', 'grade',
               existing_type=sa.String(length=5),
               type_=postgresql.ENUM('A', 'B', 'C', 'D', 'E', name='grade_class'),
               existing_nullable=False)
    op.drop_constraint(None, 'kpi_values', type_='foreignkey')
    op.create_unique_constraint(op.f('uq_kpi_value_record_key'), 'kpi_values', ['record_id', 'kpi_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_kpi_values_record_id'), 'kpi_values', ['record_id'], unique=False)
    op.create_index(op.f('idx_kpi_under'), 'kpi_values', ['kpi_key', 'achievement_ratio'], unique=False, postgresql_where='(achievement_ratio < 1.0)')
    op.create_index(op.f('idx_employees_team_id'), 'employees', ['team_id'], unique=False)
    op.create_index(op.f('idx_employees_name_trgm'), 'employees', ['name'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_employees_external_id'), 'employees', ['employee_id'], unique=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
